config/routes.rb
Rails.application.routes.draw do
  get 'persons/profile'

  resources :ttts

  post 'ttts/:id/move/:position', to: "ttts#move", as: 'add_move'

  devise_for :users
  get 'persons/profile', as: 'user_root'
  root to: "home#index"

end

app/models/move.rb
class Move < ActiveRecord::Base
  belongs_to :user
  belongs_to :ttt

  validate :if_ttt_active, on: :create
  validate :check_if_occuppied, on: :create
  validate :is_users_turn, on: :create
  validates :position, numericality: { only_integer: true, less_than: 9 }
  validate :max_move

  after_create :check_win
  validate :is_draw

  def is_draw
    errors.add(:ttt_id, "Draw game!") if ttt.is_draw?
  end

  def if_ttt_active
    errors.add(:ttt_id, "Game over!") if !ttt.is_match_active?
  end

  def check_win
    # self.errors.add(:mark, "Game over!") if ttt.is_player_win?(user.id)
    ttt.match_won
  end

  def max_move
    ttt.moves.count < 10
  end

  def check_if_occuppied
    positions = ttt.moves.map {|move| move.position}
    self.errors.add(:position, "Already taken") if positions.include? self.position
  end

  def is_users_turn
   errors.add(:user_id, "it's not your turn!") unless ttt.whose_turn.id == user_id
   ttt.reload
  end

end

app/models/ttt.rb
class Ttt < ActiveRecord::Base
  belongs_to :player_x, class_name: 'User', foreign_key: 'player_x_id'
  belongs_to :player_o, class_name: 'User', foreign_key: 'player_o_id'
  has_many :moves
  validates :player_x_id, presence: true
  validates :player_o_id, presence: true

  scope :winners, -> { where('win_id is not null') }

  WIN_LINES = [[0, 1 ,2], [3, 4, 5], [6, 7, 8], [0, 3, 6],
  [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]]

  def whose_turn
   if moves.last.try(:user_id) == player_x_id
     player_o
   else
     player_x
   end
  end

  def is_player_win?(user_id)
    user_moves = moves.map { |move| move.position if move.user_id == user_id }.compact
    WIN_LINES.map { |win| (win - user_moves).empty?}.include?(true)
  end

##
  def match_won
    WIN_LINES.each do |combo|
      if (get_player_combo(player_x_id) & combo).sort == combo.sort
        set_winner(player_x_id)
        return true
      elsif (get_player_combo(player_o_id) & combo).sort == combo.sort
        set_winner(player_o_id)
        return true
      end
    end
    return false
  end

  def set_winner(user_id)
    self.win_id = user_id
    save
  end

  def is_match_active?
    moves.count < 9 && self.win_id.nil?
  end
##

  def get_player_combo(user_id)
    moves.map { |move| move.position if move.user_id == user_id }.compact
  end

  def add_move(user_id, position)
    moves.create(user_id: user_id, position: position)
  end

  def is_draw?
    if (moves.count == 9) && (is_player_win?(self.player_x_id) == false) &&  (is_player_win?(self.player_o_id) == false)
      true
    else
      false
    end
  end

  def self.leader_board
    t = Ttt.winners
    res=Hash[t.map {|p| p.win_id}.group_by {|x| x}.map {|k,v| [k,v.count]}]
    res.sort_by(&:last).reverse.map {|k , v|  " #{User.find(k).name} won: #{v} game(s) "}
    # res
  end

  def ai
    all_positions = [0,1,2,3,4,5,6,7,8]
    occupied_position = self.moves.map(&:position)
    if !occupied_position.include?(4)
      available_positions = 4
    else
      available_positions = (all_positions - occupied_position).sample
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :x_ttts, class_name: 'Ttt', foreign_key: :player_x_id
  has_many :o_ttts, class_name: 'Ttt', foreign_key: :player_o_id
  has_many :moves

  def all_matches
    x_ttts + o_ttts
  end

  def active_matches
    self.x_ttts.map {|m| m if m.is_match_active?}.compact + self.o_ttts.map {|m| m if m.is_match_active?}.compact
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_devise_params, if: :devise_controller?
     def configure_devise_params
       devise_parameter_sanitizer.for(:sign_up) do |u|
         u.permit(:name, :avatar, :email, :password, :password_confirmation)
       end
     end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile

  end
end

app/controllers/ttts_controller.rb
class TttsController < ApplicationController

  def new
    @ttt = Ttt.new
  end

  def create
    @ttt = Ttt.new(ttt_params)
    @ttt.save
    redirect_to(@ttt)
  end

  def show
    @ttt = Ttt.find(params[:id])
  end

  def move
    @ttt = Ttt.find(params[:id])
    @move = Move.new(user_id: current_user.id, position: params[:position], ttt_id: @ttt.id)
    if @move.save
      # u = @ttt.match_won
      # raise
      if @ttt.player_o_id==10 #&& !@ttt.match_won
        # raise
        @ttt.moves.create(user_id: 10, position: @ttt.ai)
      end
      redirect_to(@ttt)
    else
      render :show
    end
  end

  private
  def ttt_params
    params.require(:ttt).permit(:player_x_id, :player_o_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/ttt_helper.rb
module TttHelper
end

app/views/home/index.html.erb
<%#= render :file => 'registrations/new' %>

<div class="register_form">
  <h3>Login to Play</h3>
   <%= form_for(:user, :url => session_path(:user)) do |f| %>
     <%= f.text_field :email %>
     <%= f.password_field :password %>
     <%#= f.check_box :remember_me %>
     <%#= f.label :remember_me %>
     <%= f.submit 'Sign in' %>
     <div>
     <%#= link_to "Forgot your password?", new_password_path(:user) %>
     </div>
     <div>
     <%= link_to "Register", new_user_registration_path %>
     </div>
   <% end %>

</div>

app/views/layouts/_registration.html.erb
<div class="swall-4 large-4 columns" >
  <div class='login'>
    <% if current_user %>
    <%= current_user.email %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    <% else %>
    <div class="button-bar">
    <ul class="stack button-group">
      <li> <%= link_to "Sign In", new_user_session_path %> </li>
      <li> <%= link_to "Register", new_user_registration_path %> </li>
    </ul>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Game Tic Tac Toe" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%#= render partial: "layouts/registration" %>

    <%= yield %>


    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/persons/profile.html.erb
<div class='login'>
  <h3>Hello <%= current_user.name.capitalize %></h3>
  <% if current_user %>
  <%#= current_user.email %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  <% else %>
  <div class="button-bar">
    <ul class="stack button-group">
      <li> <%= link_to "Sign In", new_user_session_path %> </li>
      <li> <%= link_to "Register", new_user_registration_path %> </li>
    </ul>
  </div>
  <% end %>
  <br>
  <br>
  <%= link_to (image_tag("ttt.png", width: "100px")), new_ttt_path %>
</div>

<div class="main_form">
  <div class="row">
    <div class="large-6 columns">
      <p>Active games: </p>
      <% current_user.active_matches.sort.reverse.each do |match| %>
      <%= link_to "Game #{match.id}", ttt_path(id: match.id) %>
      <br>
      <% end %>
    </div>

    <div class="large-6 columns">
      <p>Leaders:</p>
      <ol>
        <% Ttt.leader_board.each do |leader| %>
        <li>
          <%= leader %> <br>
        </li>
        <% end %>
      </ol>
    </div>
  </div>
</div>

app/views/ttts/_errors.html.erb
<% if @move && @move.errors.any? %>
<div id="error_explanation">
  <ul>
    <% @move.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  </ul>
  <% end %>
</div>
<% end %>

app/views/ttts/new.html.erb
<div class="main_form">
  <h3>Choose opponent: </h3>
  <%= form_for @ttt do |f| %>
  <%= hidden_field_tag 'ttt[player_x_id]', current_user.id  %>
  <%= f.collection_select :player_o_id, User.all, :id, :name %>
  <%= f.submit %>
  <% end %>
</div>

app/views/ttts/show.html.erb
<div class="main_form">
  <h3>Your sign is:
    <% if @ttt.player_x_id == current_user.id %>
    X
    <% else %>
    O
    <% end %>
  </h3>

  <h3>Your opponent is:
    <% if current_user.id == @ttt.player_x_id %>
    <%= User.find(@ttt.player_o_id).name %>
    <% else %>
    <%= User.find(@ttt.player_x_id).name %>
    <% end %>
  </h3>

  <% if @ttt.moves.any? && @ttt.moves.last.user_id != current_user.id %>
  <h3>your turn</h3>
  <% end %>

  <%= render partial: "errors", :locals => {move: @move} %>

  <table class="board">
    <% board = [0,1,2,3,4,5,6,7,8] %>
    <% board.each_slice(3) do |slice| %>
    <tr>
      <% slice.each do |cell| %>
      <td>
        <% if @ttt.moves.find_by_position(cell) && @ttt.moves.find_by_position(cell).user_id == @ttt.player_x_id  %>
        <%= image_tag("x_1.png") %>
        <% elsif @ttt.moves.find_by_position(cell) && @ttt.moves.find_by_position(cell).user_id == @ttt.player_o_id  %>
        <%= image_tag("o.png") %>
        <% else %>

        <%= link_to (image_tag("white-square.png")), add_move_path(id: @ttt.id, position: cell), method: :post %>

        <% end %>
      </td>
      <% end %>
    </tr>
    <% end %>
  </table>
  <br>

  <%= @errors %>

  <%= link_to "Back", user_root_path %>

</div>